### ISSUE TITLE
bug: RC Data problem with pharmacy

### ISSUE THREAD

**Issue by CyhnYldz** [acikkaynak/deprem-yardim-frontend#981]
## Bug Definition
Wrong data opens when clicked on pharmacy

-- Please add discord contact information
** discord username: `Ceyhun Yıldız#6679`

## Bug environment

rc.afetharita.com

## Describe how you are producing the bug step by step

problem pharmacy id's with lack of detail as follows
121207
121214
121230
121264
121269
121277
121290
121323
121327
121331

problem pharmacy id's with code information as follows
120103
120111

## Expected Behaviour
pharmacy detail

## Screen shots
![Ekran görüntüsü 2023-02-14 170532](https://user-images.githubusercontent.com/111140617/218775967-90ba7ef5-45ec-4ef7-ab1d-8b2f1275cdb1.png)
![Ekran görüntüsü 2023-02-14 164505](https://user-images.githubusercontent.com/111140617/218775994-625d989f-9841-411d-8b7f-30395c87568d.png)

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by dopplerDistortion** [comment]
I am not sure about supporting html injection.

**Comment by oguzergul** [comment]
this issue was backend related and fixed now. you can check it again now @sevilayerkan @CyhnYldz

**Comment by CyhnYldz** [comment]
Hi. 
problem pharmacy id's with code information as follows
120103
120111
fixed but 

problem pharmacy id's with lack of detail as follows
121207
121214
121230
121264
121269
121277
121290
121323
121327
121331
still reproducable. when you click on tem we still have nan response

**Comment by el** [comment]
I am going to take a look at this. Thanks for reporting it.

**Comment by CyhnYldz** [comment]
Not fixed "non" elements are still in data and visable With #991 
problem pharmacy id's with lack of detail as follows
121207
121214
121230
121264
121269
121277
121290
121323
121327
121331
still reproducable. when you click on tem we still have nan response

**Comment by CyhnYldz** [comment]
HTML codes came back
problem pharmacy id's with code information as follows
1545879
1545887

**Comment by CyhnYldz** [comment]
Also there is problem with some ahbap data
![Ekran görüntüsü 2023-02-15 153712](https://user-images.githubusercontent.com/111140617/219029366-35905373-ebb8-4ba3-b32c-3dc799a959ec.png)
